# Generated by Django 3.0.6 on 2020-06-04 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='houses',
            name='image',
        ),
        migrations.RemoveField(
            model_name='houses',
            name='sel',
        ),
        migrations.RemoveField(
            model_name='houses',
            name='status',
        ),
    ]
