# Generated by Django 3.0.6 on 2020-06-04 21:07

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0002_auto_20200604_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='houses',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='houses',
            name='sel',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default='1', max_length=6),
        ),
        migrations.AddField(
            model_name='houses',
            name='status',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('N', 'Nuevo'), ('U', 'Usado')], default='N', max_length=2),
        ),
    ]
