# Generated by Django 3.0.6 on 2020-06-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0003_auto_20200604_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='image',
            field=models.ImageField(default='images/housePics/none1.jpg', upload_to='images/housePics/'),
        ),
    ]
