# Generated by Django 3.0.6 on 2020-06-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0005_auto_20200604_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='image',
            field=models.ImageField(default='CRUD/static/images/housePics/none1.jpg', upload_to='CRUD/static/images/housePics/'),
        ),
    ]
