# Generated by Django 3.0.6 on 2020-06-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0006_auto_20200604_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='image',
            field=models.ImageField(default='images/none1.jpg', upload_to='images/'),
        ),
    ]
