# Generated by Django 3.0.6 on 2020-06-05 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0009_auto_20200605_0323'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
